"""
String constants used in metadata transformation
"""

METADATA_SCHEMA = "$schema"
METADATA_AT_ID = "@id"
METADATA_LABEL = "label"
METADATA_IDENTIFIER = "identifier"
METADATA_SAMPLE_IDENTIFIER = "sample_identifier"
METADATA_DESCRIPTION = "description"
METADATA_HAS_CONTEXT_CATEGORY = "has_context_category"
METADATA_HAS_CONTEXT_CATEGORY_CONFIDENCE = "has_context_category_confidence"
METADATA_HAS_MATERIAL_CATEGORY = "has_material_category"
METADATA_HAS_MATERIAL_CATEGORY_CONFIDENCE = "has_material_category_confidence"
METADATA_HAS_SAMPLE_OBJECT_TYPE = "has_sample_object_type"
METADATA_HAS_SAMPLE_OBJECT_TYPE_CONFIDENCE = "has_sample_object_type_confidence"
METADATA_INFORMAL_CLASSIFICATION = "informal_classification"
METADATA_KEYWORDS = "keywords"
METADATA_KEYWORD = "keyword"
METADATA_SCHEME_NAME = "scheme_name"
METADATA_KEYWORD_URI = "keyword_uri"
METADATA_PRODUCED_BY = "produced_by"
METADATA_RESPONSIBILITY = "responsibility"
METADATA_HAS_FEATURE_OF_INTEREST = "has_feature_of_interest"
METADATA_RESULT_TIME = "result_time"
METADATA_SAMPLING_SITE = "sampling_site"
METADATA_SAMPLE_LOCATION = "sample_location"
METADATA_LOCATION = "location"
METADATA_ELEVATION = "elevation"
METADATA_LATITUDE = "latitude"
METADATA_LONGITUDE = "longitude"
METADATA_PLACE_NAME = "place_name"
METADATA_SUBSAMPLE = "subsample"
METADATA_REGISTRANT = "registrant"
METADATA_SAMPLING_PURPOSE = "sampling_purpose"
METADATA_CURATION = "curation"
METADATA_ACCESS_CONSTRAINTS = "access_constraints"
METADATA_CURATION_LOCATION = "curation_location"
METADATA_RELATED_RESOURCE = "related_resource"
METADATA_RELATIONSHIP = "relationship"
METADATA_TARGET = "target"
METADATA_AUTHORIZED_BY = "authorized_by"
METADATA_COMPLIES_WITH = "complies_with"
METADATA_ROLE = "role"
METADATA_NAME = "name"
METADATA_LAST_MODIFIED_TIME = "last_modified_time"
